require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.nvim-tree-sitter")
require("core.plugin_config.undotree")
require("core.plugin_config.telescope")
require("core.plugin_config.pomodoro")
require("core.plugin_config.theme")
