require("core.plugin_config.lualine")
require("core.plugin_config.neo-tree")
require("core.plugin_config.nvim-tree-sitter")
require("core.plugin_config.undotree")
require("core.plugin_config.telescope")
